### PR TITLE
Bug: remove unnecessary error

### LINKED ISSUE #163: remove unnecessary error in node stdout.txt
If no custom scripts are given, an error is logged on the node when [this line](https://github.com/Azure/aztk/blob/master/node_scripts/setup_node.sh#L42) executes.

Since the files are chmod'd in the container before they are run this line is not necessary at all.

### PR DESCRIPTION
**Pull request by jafreck**
Fix #163

### CODE REVIEW

File: node_scripts/setup_node.sh [hunk 1]
```diff
@@ -39,7 +39,6 @@ fi
 # Unzip resource files and set permissions
 apt-get -y install unzip
 chmod 777 $AZ_BATCH_TASK_WORKING_DIR/docker_main.sh
-chmod -R 777 $AZ_BATCH_TASK_WORKING_DIR/custom-scripts
```
Comment (timotheeguerin) [inline node_scripts/setup_node.sh]: wait isn't that needed to run the custom scripts?

Comment (jafreck) [reply node_scripts/setup_node.sh]: No - we chmod each script on the node before we run it, (here)[https://github.com/jafreck/aztk/blob/bug/remove-chmod-error/node_scripts/install/scripts.py#L47]. This was just causing an unnecessary error if the custom-scripts directory didn't exist.
